// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlhoQkMSXXKiW8UlfgTeolztxVHuiSVKs',
    appId: '1:363634487533:web:42c8ef221ff61d49325ce4',
    messagingSenderId: '363634487533',
    projectId: 'ecommerceapp-44ea5',
    authDomain: 'ecommerceapp-44ea5.firebaseapp.com',
    storageBucket: 'ecommerceapp-44ea5.appspot.com',
    measurementId: 'G-GY7QSF8CLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2a_hRzk0TKjQ9eqTXoLAwoeMABJ5RQ9Q',
    appId: '1:363634487533:android:c7117d372a34e406325ce4',
    messagingSenderId: '363634487533',
    projectId: 'ecommerceapp-44ea5',
    storageBucket: 'ecommerceapp-44ea5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA26kQJsgPkPDXhhbIGnJfbz4E2tYMJRdE',
    appId: '1:363634487533:ios:80497ac3f6ee1b1b325ce4',
    messagingSenderId: '363634487533',
    projectId: 'ecommerceapp-44ea5',
    storageBucket: 'ecommerceapp-44ea5.appspot.com',
    androidClientId: '363634487533-qpflupbvnnfm4ij5og6etubeujshffi4.apps.googleusercontent.com',
    iosClientId: '363634487533-397bvmlb9c5eatfp15d56o6gqbieqlnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

}